// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsuTy2ubp_5oNWtl3aAgPT7n51TYwd_MQ',
    appId: '1:914887020458:web:47e69291baf86d4960e5d3',
    messagingSenderId: '914887020458',
    projectId: 'spotify01-13880',
    authDomain: 'spotify01-13880.firebaseapp.com',
    storageBucket: 'spotify01-13880.firebasestorage.app',
    measurementId: 'G-K3P04RLKEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUZmQ0BsbT73AOHWTHieSLxLQKOz4SjM',
    appId: '1:914887020458:android:b2e5a5591d65a2b660e5d3',
    messagingSenderId: '914887020458',
    projectId: 'spotify01-13880',
    storageBucket: 'spotify01-13880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Sr3N1FT01wa41Dk2sXBbgHd3Z2tw7-Q',
    appId: '1:914887020458:ios:d0b8cd5a5a78a72160e5d3',
    messagingSenderId: '914887020458',
    projectId: 'spotify01-13880',
    storageBucket: 'spotify01-13880.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );
}
